#!/usr/local/bin/perl
#
#  (c) Copyright 2005, Hewlett-Packard Development Company, LP
#
#  See the file named COPYING for license details
#


while(<STDIN>) {
    next if m!Warning: -L\.\. changed to -L.*Lintel/perl/..!o;
    next if m!Note \(probably harmless\): No library found for -lLintel\.O!o;
    next if m!Checking if your kit is complete!o;
    next if m!Looks good!o;
    next if m!Writing Makefile for Lintel!o;
    next if m!Make.common.*.make.depend: No such file or directory!o;
    next if m!Rebuilding dependencies!o;
    next if m!At least one PA 2.0 object file!o;
    next if m!No differences encountered!o;
    if(m!makedepend: warning.*more than once!o) {
	$_ = <STDIN>;
	print "$0 fail, expected Already have\n" unless /Already have/o;
	$_ = <STDIN>;
	print "$0 fail, expected /usr/include/sys/stdsyms.h\n"
	    unless m!/usr/include/sys/stdsyms.h!o;
	$_ = <STDIN>;
	print "$0 fail, expected /usr/include/sys/types.h\n"
	    unless m!/usr/include/sys/types.h!o;
    }
    if (m!Warning 829: "Lintel\.c", line \d+ \# Implicit conversion!o) {
	$_ = <STDIN>;
	print "$0 fail, expected XS_VERSION or __FILE___..."
	    unless m!XS_VERSION_BOOTCHECK!o || m!file = __FILE__;!o;
	$_ = <STDIN>;
	print "$0 fail, expected ^^^^^^^^..."
	    unless m!\^{8}!o;
	next;
    }
    if (m!Warning 749: "Lintel\.c", line \d+ \# The cast from 'cv \*' to 'sv \*' is!o) {
	$_ = <STDIN>;
	print "$0 fail, expected newXSproto...\n"
	    unless m!^\s+newXSproto\(!o;
	$_ = <STDIN>;
	print "$0 fail, expected ^^^^^^^^..."
	    unless m!\^\^\^\^\^\^\^\^!o;
	next;
    }
    next if m!blib/!o;
    print;
}

		
