# Find the Lintel includes and library
#
#  LINTEL_INCLUDE_DIR - where to find Lintel/LintelAssert.H, ...
#  LINTEL_LIBRARIES   - List of libraries when using Lintel
#  LINTEL_FOUND       - True if Lintel found.


IF (LINTEL_INCLUDE_DIR)
  # Already in cache, be silent
  SET(LINTEL_FIND_QUIETLY TRUE)
ENDIF (LINTEL_INCLUDE_DIR)

FIND_PATH(LINTEL_INCLUDE_DIR Lintel/LintelAssert.H
  ${CMAKE_INSTALL_PREFIX}/include
)

FIND_LIBRARY(LINTEL_LIBRARY 
  NAMES Lintel 
  PATHS ${CMAKE_INSTALL_PREFIX}/lib)

IF (LINTEL_INCLUDE_DIR AND LINTEL_LIBRARY)
   SET(LINTEL_FOUND TRUE)
   SET(LINTEL_LIBRARIES ${LINTEL_LIBRARY})
ELSE (LINTEL_INCLUDE_DIR AND LINTEL_LIBRARY)
   SET(LINTEL_FOUND FALSE)
   SET(LINTEL_LIBRARIES)
ENDIF (LINTEL_INCLUDE_DIR AND LINTEL_LIBRARY)

IF (LINTEL_FOUND)
   IF (NOT LINTEL_FIND_QUIETLY)
      MESSAGE(STATUS "Found Lintel: ${LINTEL_LIBRARY}")
   ENDIF (NOT LINTEL_FIND_QUIETLY)
ELSE (LINTEL_FOUND)
   IF (LINTEL_FIND_REQUIRED)
      MESSAGE(STATUS "Looked for Lintel libraries named Lintel in ${CMAKE_INSTALL_PREFIX}/lib and system paths")
      MESSAGE(STATUS "got: LINTEL_INCLUDE_DIR=${LINTEL_INCLUDE_DIR}")
      MESSAGE(STATUS "got: LINTEL_LIBRARY=${LINTEL_LIBRARY}")
      MESSAGE(FATAL_ERROR "ERROR: Could NOT find Lintel library")
   ENDIF (LINTEL_FIND_REQUIRED)
ENDIF (LINTEL_FOUND)

MARK_AS_ADVANCED(
  LINTEL_LIBRARY
  LINTEL_INCLUDE_DIR
)
